# Generated by Django 5.1.7 on 2025-03-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_message_id', models.CharField(default='', max_length=100, unique=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(default='slack', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=50)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='feedback.feedback')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to='feedback.slackuser'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='feedback.slackuser'),
        ),
        migrations.CreateModel(
            name='TaggedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_mentioned', models.CharField(max_length=100)),
                ('slack_id_mentioned', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_users', to='feedback.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.slackuser')),
            ],
        ),
    ]
