# Generated by Django 5.1.6 on 2025-02-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_reactions_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='slack_message_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TaggedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_mentioned', models.CharField(max_length=100)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_users', to='feedback.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.slackuser')),
            ],
        ),
    ]
