# Generated by Django 5.1.6 on 2025-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_slack_message_id_taggeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeduser',
            name='slack_id_mentioned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
