# Generated by Django 5.1.6 on 2025-02-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_taggeduser_slack_id_mentioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(default='slack', max_length=50),
        ),
    ]
