# Generated by Django 5.1.6 on 2025-03-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_remove_reaction_user_reaction_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='count',
        ),
    ]
