"""
Django settings for slack_feedback project.

Generated by 'django-admin startproject' using Django 5.0.7.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

SLACK_BOT_TOKEN = os.getenv('SLACK_BOT_TOKEN')
SLACK_CHANNEL_ID = os.getenv('SLACK_CHANNEL_ID')

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ut4(t#p=%z-tlvrj4bfdvkem=4um(iwc2u^4^7talmop4jve@^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Update ALLOWED_HOSTS to include your Zrok domain
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'm96gdimbv8yr.share.zrok.io',  # Add your specific Zrok domain
    '.share.zrok.io',  # This will allow any subdomain of share.zrok.io
]

# Site ID for Django Allauth
SITE_ID = 4

# Authentication Redirects
LOGIN_REDIRECT_URL = "/oauth/success/"
LOGOUT_REDIRECT_URL = "http://localhost:5173//login"

ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"

# Application definition
INSTALLED_APPS = [
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'feedback',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Django Allauth Configuration
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_LINK = True  # Automatically links social accounts with matching email

# Automatically link social accounts to existing users
ACCOUNT_UNIQUE_EMAIL = True  # Ensures each email is unique across accounts
SOCIALACCOUNT_AUTO_SIGNUP = True

# Google OAuth Configuration
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email", "openid"],
        "OAUTH_PKCE_ENABLED": True,
        "AUTH_PARAMS": {"access_type": "offline"},
        "CALLBACK_URL": "http://localhost:8000/accounts/google/login/callback/",
        "PROMPT_SELECT_ACCOUNT": True,  # Forces Google account selection each time
    }
}

# Google OAuth Keys
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = (
    "953127088108-apsbelk5grvb0l949mu18khfqq651oka"
    ".apps.googleusercontent.com"
)
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "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"

# In settings.py
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Use custom SocialAccount Adapter
SOCIALACCOUNT_ADAPTER = "feedback.adapters.MySocialAccountAdapter"

# Restrict login to Workspace domain
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False
SOCIALACCOUNT_DOMAIN_WHITELIST = ["arbisoft.com"]

ACCOUNT_SIGNUP_REDIRECT_URL = "/"

ROOT_URLCONF = 'slack_feedback.urls'

# Templates Configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'slack_feedback.wsgi.application'

# Database Configuration (Default: SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password Validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static Files Configuration
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cookie Settings
SESSION_COOKIE_SAMESITE = 'None'  # Required for cross-site
SESSION_COOKIE_SECURE = True      # Required when SameSite is 'None'
CSRF_COOKIE_SAMESITE = 'None'    # Required for cross-site
CSRF_COOKIE_SECURE = True        # Required when SameSite is 'None'
SESSION_COOKIE_HTTPONLY = True

# CORS Settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'https://feedbackviewer.netlify.app',
    'http://localhost:5173',
    'http://localhost:8000'
]

# For development only - remove in production
CORS_ORIGIN_ALLOW_ALL = False

# Update your CSRF settings
CSRF_TRUSTED_ORIGINS = [
    'https://feedbackviewer.netlify.app',
    'http://localhost:5173',
    'http://localhost:8000'
]

# Ensure cookies work on localhost
CSRF_COOKIE_DOMAIN = None
SESSION_COOKIE_DOMAIN = None

# Add these settings
SOCIALACCOUNT_LOGIN_ON_GET = True  # Removes the intermediate "Continue" page
ACCOUNT_LOGOUT_ON_GET = True  # Removes the intermediate logout confirmation
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'
ACCOUNT_SESSION_REMEMBER = True

# Add to your existing settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'slack_events.log',
        },
    },
    'loggers': {
        'feedback.views': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
    },
}
